name: Nanopi_R1s_H5_lean

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: repo install
      run: |
        git clone https://github.com/friendlyarm/repo
        sudo cp repo/repo /usr/bin/
    - name: rsync h5 code
      run: |
        mkdir friendlywrt-h5
        cd friendlywrt-h5
        repo init -u https://github.com/friendlyarm/friendlywrt_manifests -b master-v18.06.1 -m h5.xml --repo-url=https://github.com/friendlyarm/repo  --no-clone-bundle
        repo sync -c  --no-clone-bundle
    - name: install build base
      run: |
        wget -O - https://raw.githubusercontent.com/friendlyarm/build-env-on-ubuntu-bionic/master/install.sh | bash
    - name: building
      run: |
        cd friendlywrt-h5
        ./build.sh nanopi_r1s.mk
